plugin:
  prefix: "&bKoth &8» &f"
  version: "1.0.0"
  author: "Bughatti"

messages:
  no-permission: "%prefix%&cNo tienes permisos para usar este comando."
  capturing-interval-seconds: 5
  capturing: "%prefix%¡El jugador &e%player% &festá capturando el Koth &e%koth%&f!"
  koth-created: "%prefix%&aEl koth &e%koth% &afue creado correctamente."
  koth-not-found: "%prefix%&cEse koth no existe."
  koth-started: "%prefix%&a¡El koth &e%koth% &aha comenzado!"
  koth-stopped: "%prefix%&c¡El koth &e%koth% &cha finalizado!"
  koth-won: "%prefix%&a¡&e%player% &aha ganado el koth &e%koth%&a!"
  wand-given: "%prefix%&aRecibiste la wand de selección. Click izquierdo = zona 1, click derecho = zona 2."
  pos1-set: "%prefix%&aPosición 1 marcada."
  pos2-set: "%prefix%&aPosición 2 marcada."
  utilities-set: "%prefix%&aUtilities del koth &e%koth% &aen &e%value%&a."
  keepinventory-set: "%prefix%&akeepInventory del koth &e%koth% &aen &e%value%&a."
  duration-set: "%prefix%&aDuración del koth &e%koth% &aestablecida en &e%minutes% &aminutos."
  utilities-blocked: "%prefix%&cNo podés usar lana ni telas dentro de este koth."

titles:
  enter-title: "&x&0&0&D&A&F&F&lF&x&1&4&D&E&F&F&lU&x&2&8&E&2&F&F&lL&x&3&C&E&6&F&F&lL&x&5&0&E&9&F&F&lP&x&6&4&E&D&F&F&lV&x&7&8&F&1&F&F&lP"
  enter-subtitle: "&x&0&0&D&A&F&F¡Estas capturando el Koth! 🏹"
  leave-title: "&x&0&0&D&A&F&F&lF&x&1&4&D&E&F&F&lU&x&2&8&E&2&F&F&lL&x&3&C&E&6&F&F&lL&x&5&0&E&9&F&F&lP&x&6&4&E&D&F&F&lV&x&7&8&F&1&F&F&lP"
  leave-subtitle: "&x&0&0&D&A&F&F¡Dejaste de capturar el Koth! 🏹"
  fade-in: 10
  stay: 40
  fade-out: 10

schedule:
  timezone: "America/Argentina/Buenos_Aires"

koths: {}
