name: DayKoths
version: '1.0.0'
main: com.bughatti.daykoths.DayKoths
api-version: '1.20'
author: Bughatti
commands:
  daykoths:
    aliases: [dkoths, dk]
    description: Comando principal de DayKoths
permissions:
  daykoths.admin:
    default: op
